CREATE TABLE artist
(
    artist_id       INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , artist_name   VARCHAR(255)    NOT NULL
    , is_active     BOOLEAN         NOT NULL
    , created_utc   TIMESTAMPTZ     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by    VARCHAR(255)    NOT NULL DEFAULT (CURRENT_USER)
    , modified_utc  TIMESTAMPTZ         NULL
    , modified_by   VARCHAR(255)        NULL
);
 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE artist IS 'Data about individual artists';

/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN artist.artist_id    IS 'PK, IDENTITY';
COMMENT ON COLUMN artist.artist_name  IS 'The name of the artist';
COMMENT ON COLUMN artist.is_active    IS 'Is the artist still making music?';
COMMENT ON COLUMN artist.created_utc  IS 'When the record was created in UTC';
COMMENT ON COLUMN artist.created_by   IS 'Who created the record';
COMMENT ON COLUMN artist.modified_utc IS 'When the record was modified in UTC';
COMMENT ON COLUMN artist.modified_by  IS 'Who modified the record';