CREATE TABLE artist_group_membership
(
    artist_group_membership_id  INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , artist_group_id           INT             NOT NULL
    , artist_id                 INT             NOT NULL
    , created_utc               TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by                VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc              TIMESTAMPTZ         NULL
    , modified_by               VARCHAR(255)        NULL
    , CONSTRAINT pk_artist_group_membership PRIMARY KEY (artist_group_membership_id)
);

/*
-- ==================================
-- INDEXES
-- ==================================
*/
CREATE UNIQUE INDEX ux__artist_group_membership__artist_group_id__artist_id
ON artist_group_membership
(
    artist_group_id
    , artist_id
);
 
/*
-- ==================================
-- CONSTRAINTS
-- ==================================
*/
ALTER TABLE artist_group_membership
ADD CONSTRAINT fk_artist_group_membership_group_id
FOREIGN KEY (artist_group_id)
REFERENCES artist_group (artist_group_id);
 
ALTER TABLE artist_group_membership
ADD CONSTRAINT fk_artist_group_membership_artist_id
FOREIGN KEY (artist_id)
REFERENCES artist (artist_id);

/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE artist_group_membership IS 'Tracks artist memberships in groups';

/*
-- ==================================
-- TRIGGER
-- ==================================
*/
CREATE OR REPLACE trg_artist_group_membership_set_modified_utc
    AFTER UPDATE ON artist_group_membership
    FOR EACH ROW
    EXECUTE FUNCTION set_modified_utc();