CREATE TABLE artist_group
(
    artist_group_id         INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , artist_group_name     VARCHAR(255)    NOT NULL
    , is_active             BOOLEAN         NOT NULL
    , created_utc           TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by            VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc          TIMESTAMPTZ         NULL
    , modified_by           VARCHAR(255)        NULL
    , CONSTRAINT pk_artist_group PRIMARY KEY (artist_group_id)
);
 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE artist_group IS 'Data about groups of artists or single artists';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN artist_group.artist_group_id      IS 'PK, IDENTITY';
COMMENT ON COLUMN artist_group.artist_group_name    IS 'The name of the group';
COMMENT ON COLUMN artist_group.is_active            IS 'Is the group still making music/together?';
COMMENT ON COLUMN artist_group.created_utc          IS 'When the record was created in UTC';
COMMENT ON COLUMN artist_group.created_by           IS 'Who created the record';
COMMENT ON COLUMN artist_group.modified_utc         IS 'When the record was modified in UTC';
COMMENT ON COLUMN artist_group.modified_by          IS 'Who modified the record';

/*
-- ==================================
-- TRIGGER
-- ==================================
*/
CREATE TRIGGER trg_artist_group_set_modified_utc
    BEFORE UPDATE ON artist_group
    FOR EACH ROW
    EXECUTE FUNCTION set_modified_utc();