CREATE TABLE genre
(
    genre_id            INT             GENERATED BY DEFAULT AS IDENTITY
    , genre_name        VARCHAR(255)    NOT NULL
    , "description"     VARCHAR(4000)   NOT NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
    , CONSTRAINT pk_genre PRIMARY KEY (genre_id)
);
 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE genre IS 'Data about genres';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN genre.genre_id    IS 'PK, IDENTITY';
COMMENT ON COLUMN genre.genre_name  IS 'The name of the genre';
COMMENT ON COLUMN genre.description IS 'A brief description of the genre';
COMMENT ON COLUMN genre.created_utc IS 'When the record was created in UTC';
COMMENT ON COLUMN genre.created_by  IS 'Who created the record';
COMMENT ON COLUMN genre.modified_utc IS 'When the record was modified in UTC';
COMMENT ON COLUMN genre.modified_by  IS 'Who modified the record';

/*
-- ==================================
-- TRIGGER
-- ==================================
*/
CREATE TRIGGER trg_genre_set_modified_utc
    AFTER UPDATE ON genre
    FOR EACH ROW
    EXECUTE FUNCTION set_modified_utc();