CREATE TABLE producer_group
(
    producer_group_id       INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , producer_group_name   VARCHAR(255)    NOT NULL
    , is_active             BOOLEAN         NOT NULL
    , created_utc           TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by            VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc          TIMESTAMPTZ         NULL
    , modified_by           VARCHAR(255)        NULL
);
 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE producer_group IS 'Data about groups of producers or individual producers';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN producer_group.producer_group_id   IS 'PK, IDENTITY';
COMMENT ON COLUMN producer_group.producer_group_name IS 'The name of the producer group/producer';
COMMENT ON COLUMN producer_group.is_active           IS 'Is the producer group still together/making music?';
COMMENT ON COLUMN producer_group.created_utc         IS 'When the record was created in UTC';
COMMENT ON COLUMN producer_group.created_by          IS 'Who created the record';
COMMENT ON COLUMN producer_group.modified_utc        IS 'When the record was modified in UTC';
COMMENT ON COLUMN producer_group.modified_by         IS 'Who modified the record';
