CREATE TABLE producer
(
    producer_id     INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , producer_name VARCHAR(255)    NOT NULL
    , is_active     BOOLEAN         NOT NULL
    , created_utc   TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by    VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc  TIMESTAMPTZ         NULL
    , modified_by   VARCHAR(255)        NULL
    , CONSTRAINT pk_producer PRIMARY KEY (producer_id)
);
 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE producer IS 'Data about individual producers';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN producer.producer_id   IS 'PK, IDENTITY';
COMMENT ON COLUMN producer.producer_name IS 'The name of the producer';
COMMENT ON COLUMN producer.is_active     IS 'Is the producer still producing?';
COMMENT ON COLUMN producer.created_utc   IS 'When the record was created in UTC';
COMMENT ON COLUMN producer.created_by    IS 'Who created the record';
COMMENT ON COLUMN producer.modified_utc  IS 'When the record was modified in UTC';
COMMENT ON COLUMN producer.modified_by   IS 'Who modified the record';

/*
-- ==================================
-- TRIGGER
-- ==================================
*/
CREATE OR REPLACE trg_producer_set_modified_utc
    AFTER UPDATE ON producer
    FOR EACH ROW
    EXECUTE FUNCTION set_modified_utc();