CREATE TABLE producer
(
    producer_id     INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , producer_name VARCHAR(255)    NOT NULL
    , is_active     BOOLEAN         NOT NULL
    , created_utc   TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by    VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc  TIMESTAMPTZ
    , modified_by   VARCHAR(255)
);
 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE producer IS 'Data about individual producers';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN producer.producer_id   IS 'PK, IDENTITY';
COMMENT ON COLUMN producer.producer_name IS 'The name of the producer';
COMMENT ON COLUMN producer.is_active     IS 'Is the producer still producing?';
COMMENT ON COLUMN producer.created_utc   IS 'When the record was created in UTC';
COMMENT ON COLUMN producer.created_by    IS 'Who created the record';
COMMENT ON COLUMN producer.modified_utc  IS 'When the record was modified in UTC';
COMMENT ON COLUMN producer.modified_by   IS 'Who modified the record';
