CREATE TABLE project_type
(
    project_type_id     INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , project_type_name VARCHAR(255)    NOT NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
);
 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE project_type IS 'Types of musical projects';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN project_type.project_type_id   IS 'PK, IDENTITY';
COMMENT ON COLUMN project_type.project_type_name IS 'The type of musical project';
COMMENT ON COLUMN project_type.created_utc       IS 'When the record was created in UTC';
COMMENT ON COLUMN project_type.created_by        IS 'Who created the record';
COMMENT ON COLUMN project_type.modified_utc      IS 'When the record was modified in UTC';
COMMENT ON COLUMN project_type.modified_by       IS 'Who modified the record';
