CREATE TABLE project
(
    project_id          INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , project_name      VARCHAR(255)    NOT NULL
    , artist_group_id   INT             NOT NULL
    , scene_id          INT                 NULL
    , project_type_id   INT             NOT NULL
    , release_date      DATE            NOT NULL
    , rating            NUMERIC(4, 2)       NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
    , CONSTRAINT pk_project PRIMARY KEY (project_id)
);

/*
-- ==================================
-- CONSTRAINTS
-- ==================================
*/
ALTER TABLE project
ADD CONSTRAINT fk_project_artist_group_id
FOREIGN KEY (artist_group_id)
REFERENCES artist_group (artist_group_id);
 
ALTER TABLE project
ADD CONSTRAINT fk_project_scene_id
FOREIGN KEY (scene_id)
REFERENCES scene (scene_id);
 
ALTER TABLE project
ADD CONSTRAINT fk_project_project_type_id
FOREIGN KEY (project_type_id)
REFERENCES project_type (project_type_id);

 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE project IS 'Data about musical projects';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN project.project_id      IS 'PK, IDENTITY';
COMMENT ON COLUMN project.project_name    IS 'The name of the project';
COMMENT ON COLUMN project.scene_id        IS 'The musical scene of the project. References scene';
COMMENT ON COLUMN project.project_type_id IS 'The type of musical project';
COMMENT ON COLUMN project.release_date    IS 'The date the musical project was released';
COMMENT ON COLUMN project.rating          IS 'The overall rating of the musical project out of 10';
COMMENT ON COLUMN project.created_utc     IS 'When the record was created in UTC';
COMMENT ON COLUMN project.created_by      IS 'Who created the record';
COMMENT ON COLUMN project.modified_utc    IS 'When the record was modified in UTC';
COMMENT ON COLUMN project.modified_by     IS 'Who modified the record';

/*
-- ==================================
-- TRIGGER
-- ==================================
*/
CREATE TRIGGER trg_project_set_modified_utc
    BEFORE UPDATE ON project
    FOR EACH ROW
    EXECUTE FUNCTION set_modified_utc();