CREATE TABLE scene
(
    scene_id            INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , scene_name        VARCHAR(255)    NOT NULL
    , "description"     VARCHAR(4000)   NOT NULL
    , is_geographic     INT             NOT NULL    DEFAULT 0
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
);
 
/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE scene IS 'Data about musical scenes';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN scene.scene_id      IS 'PK, IDENTITY';
COMMENT ON COLUMN scene.scene_name    IS 'The name of the scene';
COMMENT ON COLUMN scene.description   IS 'A brief description of the musical scene';
COMMENT ON COLUMN scene.is_geographic IS 'Is the scene a geographic scene (e.g., East Coast Hip-Hop, UK Hip-Hop, etc.)';
COMMENT ON COLUMN scene.created_utc   IS 'When the record was created in UTC';
COMMENT ON COLUMN scene.created_by    IS 'Who created the record';
COMMENT ON COLUMN scene.modified_utc  IS 'When the record was modified in UTC';
COMMENT ON COLUMN scene.modified_by   IS 'Who modified the record';
