CREATE TABLE song
(
    song_id                 INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , song_name             VARCHAR(255)    NOT NULL
    , artist_group_id       INT             NOT NULL
    , project_id            INT             NOT NULL
    , producer_group_id     INT                 NULL
    , genre_id              INT             NOT NULL
    , scene_id              INT                 NULL
    , streaming_service_id  INT             NOT NULL
    , duration              INT             NOT NULL
    , rating                NUMERIC(4, 2)       NULL
    , is_added              BOOLEAN         NOT NULL    DEFAULT (FALSE)
    , is_local_file         BOOLEAN         NOT NULL    DEFAULT (FALSE)
    , created_utc           TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by            VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc          TIMESTAMPTZ         NULL
    , modified_by           VARCHAR(255)        NULL
    , CONSTRAINT pk_song PRIMARY KEY (song_id)
);

/*
-- ==================================
-- CONSTRAINTS
-- ==================================
*/
ALTER TABLE song
ADD CONSTRAINT fk_song_artist_group_id
FOREIGN KEY (artist_group_id)
REFERENCES artist_group (artist_group_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_project_id
FOREIGN KEY (project_id)
REFERENCES project (project_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_producer_group_id
FOREIGN KEY (producer_group_id)
REFERENCES producer_group (producer_group_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_genre_id
FOREIGN KEY (genre_id)
REFERENCES genre (genre_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_scene_id
FOREIGN KEY (scene_id)
REFERENCES scene (scene_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_service_id
FOREIGN KEY (streaming_service_id)
REFERENCES streaming_service (streaming_service_id);

ALTER TABLE song
ADD CONSTRAINT ck_song_rating
CHECK (rating >= 0.00 AND rating <= 10.00);

ALTER TABLE song
ADD CONSTRAINT ck_song_duration
CHECK (duration >= 0);

/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE song IS 'Data about individual songs';
 
/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN song.song_id           IS 'PK, IDENTITY';
COMMENT ON COLUMN song.song_name         IS 'The name of the song';
COMMENT ON COLUMN song.artist_group_id   IS 'The group performing the song. References music_group';
COMMENT ON COLUMN song.project_id        IS 'The project the song belongs to. References project';
COMMENT ON COLUMN song.producer_group_id IS 'The group of producers/producer that produced the song. References producer_group';
COMMENT ON COLUMN song.genre_id          IS 'The genre of the song. References genre';
COMMENT ON COLUMN song.scene_id          IS 'The scene of the song. References scene';
COMMENT ON COLUMN song.service_id        IS 'The source streaming service of the song. Local files are ported from other streaming services if they are not from Apple Music. References streaming_service';
COMMENT ON COLUMN song.duration          IS 'How long the song lasts in seconds';
COMMENT ON COLUMN song.rating            IS 'The song rating out of 10';
COMMENT ON COLUMN song.is_added          IS 'Flag if the song is or is not added in my library';
COMMENT ON COLUMN song.is_local_file     IS 'Flag if the song is or is not a local file';
COMMENT ON COLUMN song.created_utc       IS 'When the record was created in UTC';
COMMENT ON COLUMN song.created_by        IS 'Who created the record';
COMMENT ON COLUMN song.modified_utc      IS 'When the record was modified in UTC';
COMMENT ON COLUMN song.modified_by       IS 'Who modified the record';

/*
-- ==================================
-- TRIGGER
-- ==================================
*/
CREATE TRIGGER trg_song_set_modified_utc
    BEFORE UPDATE ON song
    FOR EACH ROW
    EXECUTE FUNCTION set_modified_utc();