CREATE TABLE streaming_service
(
    streaming_service_id            INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , streaming_service_name        VARCHAR(255)    NOT NULL
    , created_utc                   TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by                    VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc                  TIMESTAMPTZ         NULL
    , modified_by                   VARCHAR(255)        NULL
    , CONSTRAINT pk_streaming_service PRIMARY KEY (streaming_service_id)
);

COMMENT ON TABLE streaming_service IS 'The StreamingService streaming service source';
 
COMMENT ON COLUMN streaming_service.streaming_service_id    IS 'PK, IDENTITY';
COMMENT ON COLUMN streaming_service.streaming_service_name  IS 'The name of the source streaming service';
COMMENT ON COLUMN streaming_service.created_utc             IS 'When the record was created in UTC';
COMMENT ON COLUMN streaming_service.created_by              IS 'Who created the record';
COMMENT ON COLUMN streaming_service.modified_utc            IS 'When the record was modified in UTC';
COMMENT ON COLUMN streaming_service.modified_by             IS 'Who modified the record';
