CREATE TABLE user_login
(
    user_login_id       INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , username          VARCHAR(50)     NOT NULL
    , user_password     BYTEA           NOT NULL
    , login_count       INT             NOT NULL DEFAULT (0)
    , last_login_date   TIMESTAMPTZ         NULL
    , is_active         BOOLEAN         NOT NULL DEFAULT (FALSE)
    , is_admin          BOOLEAN         NOT NULL DEFAULT (FALSE)
    , created_by        VARCHAR(255)    NOT NULL DEFAULT (current_user)
    , created_utc       TIMESTAMPTZ     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
    , modified_by       VARCHAR(255)        NULL
    , modified_utc      TIMESTAMPTZ         NULL
    , CONSTRAINT pk_user_login PRIMARY KEY (user_login_id)
);

/*
-- ==================================
-- INDEXES
-- ==================================
*/
CREATE UNIQUE INDEX ux_user_login_username
ON user_login
(
    username
)
INCLUDE
(
    user_password
    , is_active
);

/*
-- ==================================
-- TABLE COMMENT
-- ==================================
*/
COMMENT ON TABLE user_login IS 'Site logins';

/*
-- ==================================
-- FIELD COMMENTS
-- ==================================
*/
COMMENT ON COLUMN user_login.user_login_id     IS 'PK, IDENTITY';
COMMENT ON COLUMN user_login.username          IS 'The login username';
COMMENT ON COLUMN user_login.user_password     IS 'Hashed password';
COMMENT ON COLUMN user_login.login_count       IS 'How many times this login has been used to login';
COMMENT ON COLUMN user_login.last_login_date   IS 'When the login was last used in UTC';
COMMENT ON COLUMN user_login.is_active         IS 'Flags if the login is active';
COMMENT ON COLUMN user_login.is_admin          IS 'Flags if the login has administrative privileges in the app';

/*
-- ==================================
-- TRIGGER
-- ==================================
*/
CREATE OR REPLACE trg_user_login_set_modified_utc
    AFTER UPDATE ON user_login
    FOR EACH ROW
    EXECUTE FUNCTION set_modified_utc();