/*
-- ==================================
-- V1__create_base_tables.sql
-- Creates all base tables with no FK dependencies
-- Tables: artist, artist_group, genre, producer, producer_group,
--         project_type, scene, streaming_service, user_login
-- ==================================
*/

/*
-- ==================================
-- artist
-- ==================================
*/
CREATE TABLE artist
(
    artist_id       INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , artist_name   VARCHAR(255)    NOT NULL
    , is_active     BOOLEAN         NOT NULL
    , created_utc   TIMESTAMPTZ     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by    VARCHAR(255)    NOT NULL DEFAULT (CURRENT_USER)
    , modified_utc  TIMESTAMPTZ         NULL
    , modified_by   VARCHAR(255)        NULL
    , CONSTRAINT pk_artist PRIMARY KEY (artist_id)
);
 
COMMENT ON TABLE artist                 IS 'Data about individual artists';
COMMENT ON COLUMN artist.artist_id      IS 'PK, IDENTITY';
COMMENT ON COLUMN artist.artist_name    IS 'The name of the artist';
COMMENT ON COLUMN artist.is_active      IS 'Is the artist still making music?';
COMMENT ON COLUMN artist.created_utc    IS 'When the record was created in UTC';
COMMENT ON COLUMN artist.created_by     IS 'Who created the record';
COMMENT ON COLUMN artist.modified_utc   IS 'When the record was modified in UTC';
COMMENT ON COLUMN artist.modified_by    IS 'Who modified the record';

/*
-- ==================================
-- artist_group
-- ==================================
*/
CREATE TABLE artist_group
(
    artist_group_id         INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , artist_group_name     VARCHAR(255)    NOT NULL
    , is_active             BOOLEAN         NOT NULL
    , created_utc           TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by            VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc          TIMESTAMPTZ         NULL
    , modified_by           VARCHAR(255)        NULL
    , CONSTRAINT pk_artist_group PRIMARY KEY (artist_group_id)
);
 
COMMENT ON TABLE artist_group                       IS 'Data about groups of artists or single artists';
COMMENT ON COLUMN artist_group.artist_group_id      IS 'PK, IDENTITY';
COMMENT ON COLUMN artist_group.artist_group_name    IS 'The name of the group';
COMMENT ON COLUMN artist_group.is_active            IS 'Is the group still making music/together?';
COMMENT ON COLUMN artist_group.created_utc          IS 'When the record was created in UTC';
COMMENT ON COLUMN artist_group.created_by           IS 'Who created the record';
COMMENT ON COLUMN artist_group.modified_utc         IS 'When the record was modified in UTC';
COMMENT ON COLUMN artist_group.modified_by          IS 'Who modified the record';

/*
-- ==================================
-- genre
-- ==================================
*/
CREATE TABLE genre
(
    genre_id            INT             GENERATED BY DEFAULT AS IDENTITY
    , genre_name        VARCHAR(255)    NOT NULL
    , "description"     VARCHAR(4000)   NOT NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
    , CONSTRAINT pk_genre PRIMARY KEY (genre_id)
);
 
COMMENT ON TABLE genre                  IS 'Data about genres';
COMMENT ON COLUMN genre.genre_id        IS 'PK, IDENTITY';
COMMENT ON COLUMN genre.genre_name      IS 'The name of the genre';
COMMENT ON COLUMN genre.description     IS 'A brief description of the genre';
COMMENT ON COLUMN genre.created_utc     IS 'When the record was created in UTC';
COMMENT ON COLUMN genre.created_by      IS 'Who created the record';
COMMENT ON COLUMN genre.modified_utc    IS 'When the record was modified in UTC';
COMMENT ON COLUMN genre.modified_by     IS 'Who modified the record';

/*
-- ==================================
-- producer
-- ==================================
*/
CREATE TABLE producer
(
    producer_id     INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , producer_name VARCHAR(255)    NOT NULL
    , is_active     BOOLEAN         NOT NULL
    , created_utc   TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by    VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc  TIMESTAMPTZ         NULL
    , modified_by   VARCHAR(255)        NULL
    , CONSTRAINT pk_producer PRIMARY KEY (producer_id)
);
 
COMMENT ON TABLE producer                   IS 'Data about individual producers';
COMMENT ON COLUMN producer.producer_id      IS 'PK, IDENTITY';
COMMENT ON COLUMN producer.producer_name    IS 'The name of the producer';
COMMENT ON COLUMN producer.is_active        IS 'Is the producer still producing?';
COMMENT ON COLUMN producer.created_utc      IS 'When the record was created in UTC';
COMMENT ON COLUMN producer.created_by       IS 'Who created the record';
COMMENT ON COLUMN producer.modified_utc     IS 'When the record was modified in UTC';
COMMENT ON COLUMN producer.modified_by      IS 'Who modified the record';

/*
-- ==================================
-- producer_group
-- ==================================
*/
CREATE TABLE producer_group
(
    producer_group_id       INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , producer_group_name   VARCHAR(255)    NOT NULL
    , is_active             BOOLEAN         NOT NULL
    , created_utc           TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by            VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc          TIMESTAMPTZ         NULL
    , modified_by           VARCHAR(255)        NULL
    , CONSTRAINT pk_producer_group PRIMARY KEY (producer_group_id)
);
 
COMMENT ON TABLE producer_group IS 'Data about groups of producers or individual producers';
COMMENT ON COLUMN producer_group.producer_group_id   IS 'PK, IDENTITY';
COMMENT ON COLUMN producer_group.producer_group_name IS 'The name of the producer group/producer';
COMMENT ON COLUMN producer_group.is_active           IS 'Is the producer group still together/making music?';
COMMENT ON COLUMN producer_group.created_utc         IS 'When the record was created in UTC';
COMMENT ON COLUMN producer_group.created_by          IS 'Who created the record';
COMMENT ON COLUMN producer_group.modified_utc        IS 'When the record was modified in UTC';
COMMENT ON COLUMN producer_group.modified_by         IS 'Who modified the record';

/*
-- ==================================
-- project_type
-- ==================================
*/
CREATE TABLE project_type
(
    project_type_id     INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , project_type_name VARCHAR(255)    NOT NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
    , CONSTRAINT pk_project_type PRIMARY KEY (project_type_id)
);
 

COMMENT ON TABLE project_type                       IS 'Types of musical projects';
COMMENT ON COLUMN project_type.project_type_id      IS 'PK, IDENTITY';
COMMENT ON COLUMN project_type.project_type_name    IS 'The type of musical project';
COMMENT ON COLUMN project_type.created_utc          IS 'When the record was created in UTC';
COMMENT ON COLUMN project_type.created_by           IS 'Who created the record';
COMMENT ON COLUMN project_type.modified_utc         IS 'When the record was modified in UTC';
COMMENT ON COLUMN project_type.modified_by          IS 'Who modified the record';

/*
-- ==================================
-- scene
-- ==================================
*/
CREATE TABLE scene
(
    scene_id            INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , scene_name        VARCHAR(255)    NOT NULL
    , "description"     VARCHAR(4000)   NOT NULL
    , is_geographic     BOOLEAN         NOT NULL    DEFAULT (FALSE)
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
    , CONSTRAINT pk_scene PRIMARY KEY (scene_id)
);
 
COMMENT ON TABLE scene                  IS 'Data about musical scenes';
COMMENT ON COLUMN scene.scene_id        IS 'PK, IDENTITY';
COMMENT ON COLUMN scene.scene_name      IS 'The name of the scene';
COMMENT ON COLUMN scene.description     IS 'A brief description of the musical scene';
COMMENT ON COLUMN scene.is_geographic   IS 'Is the scene a geographic scene (e.g., East Coast Hip-Hop, UK Hip-Hop, etc.)';
COMMENT ON COLUMN scene.created_utc     IS 'When the record was created in UTC';
COMMENT ON COLUMN scene.created_by      IS 'Who created the record';
COMMENT ON COLUMN scene.modified_utc    IS 'When the record was modified in UTC';
COMMENT ON COLUMN scene.modified_by     IS 'Who modified the record';

/*
-- ==================================
-- scene
-- ==================================
*/
CREATE TABLE streaming_service
(
    streaming_service_id            INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , streaming_service_name        VARCHAR(255)    NOT NULL
    , created_utc                   TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by                    VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc                  TIMESTAMPTZ         NULL
    , modified_by                   VARCHAR(255)        NULL
    , CONSTRAINT pk_streaming_service PRIMARY KEY (streaming_service_id)
);

COMMENT ON TABLE streaming_service                          IS 'The StreamingService streaming service source';
COMMENT ON COLUMN streaming_service.streaming_service_id    IS 'PK, IDENTITY';
COMMENT ON COLUMN streaming_service.service_name            IS 'The name of the source streaming service';
COMMENT ON COLUMN streaming_service.created_utc             IS 'When the record was created in UTC';
COMMENT ON COLUMN streaming_service.created_by              IS 'Who created the record';
COMMENT ON COLUMN streaming_service.modified_utc            IS 'When the record was modified in UTC';
COMMENT ON COLUMN streaming_service.modified_by             IS 'Who modified the record';

/*
-- ==================================
-- scene
-- ==================================
*/
CREATE TABLE user_login
(
    user_login_id       INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , username          VARCHAR(50)     NOT NULL
    , user_password     BYTEA           NOT NULL
    , login_count       INT             NOT NULL DEFAULT (0)
    , last_login_date   TIMESTAMPTZ         NULL
    , is_active         BOOLEAN         NOT NULL DEFAULT (FALSE)
    , is_admin          BOOLEAN         NOT NULL DEFAULT (FALSE)
    , created_by        VARCHAR(255)    NOT NULL DEFAULT (current_user)
    , created_utc       TIMESTAMPTZ     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
    , modified_by       VARCHAR(255)        NULL
    , modified_utc      TIMESTAMPTZ         NULL
    , CONSTRAINT pk_user_login PRIMARY KEY (user_login_id)
);

CREATE UNIQUE INDEX ux_user_login_username
ON user_login
(
    username
)
INCLUDE
(
    user_password
    , is_active
);

COMMENT ON TABLE user_login                     IS 'Site logins';
COMMENT ON COLUMN user_login.user_login_id      IS 'PK, IDENTITY';
COMMENT ON COLUMN user_login.username           IS 'The login username';
COMMENT ON COLUMN user_login.user_password      IS 'Hashed password';
COMMENT ON COLUMN user_login.login_count        IS 'How many times this login has been used to login';
COMMENT ON COLUMN user_login.last_login_date    IS 'When the login was last used in UTC';
COMMENT ON COLUMN user_login.is_active          IS 'Flags if the login is active';
COMMENT ON COLUMN user_login.is_admin           IS 'Flags if the login has administrative privileges in the app';