/*
-- ==================================
-- V2__create_dependent_tables.sql
-- Creates tables that have FK dependencies on base tables
-- Tables: artist_group_membership, genre_hierarchy, producer_group_membership,
--         project, song
-- ==================================
*/

/*
-- ==================================
-- artist_group_membership
-- ==================================
*/
CREATE TABLE artist_group_membership
(
    artist_group_id         INT             NOT NULL
    , artist_id             INT             NOT NULL
    , created_utc           TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by            VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc          TIMESTAMPTZ
    , modified_by           VARCHAR(255)
    , CONSTRAINT pk_artist_group_membership PRIMARY KEY (artist_group_id, artist_id)
);
 

ALTER TABLE artist_group_membership
ADD CONSTRAINT fk_artist_group_membership_group_id
FOREIGN KEY (artist_group_id)
REFERENCES artist_group (artist_group_id);
 
ALTER TABLE artist_group_membership
ADD CONSTRAINT fk_artist_group_membership_artist_id
FOREIGN KEY (artist_id)
REFERENCES artist (artist_id);

COMMENT ON TABLE artist_group_membership IS 'Tracks artist memberships in groups';

/*
-- ==================================
-- genre_hierarchy
-- ==================================
*/
CREATE TABLE genre_hierarchy
(
    genre_id            INT             NOT NULL
    , parent_genre_id   INT             NOT NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc      TIMESTAMPTZ
    , modified_by       VARCHAR(255)
    , CONSTRAINT pk_genre_hierarchy PRIMARY KEY (genre_id, parent_genre_id)
);

ALTER TABLE genre_hierarchy
ADD CONSTRAINT fk_genre_hierarchy_genre_id
FOREIGN KEY (genre_id)
REFERENCES genre (genre_id);
 
ALTER TABLE genre_hierarchy
ADD CONSTRAINT fk_genre_hierarchy_parent_genre_id
FOREIGN KEY (parent_genre_id)
REFERENCES genre (genre_id);

COMMENT ON TABLE genre_hierarchy                    IS 'The hierarchical organization of genres';
COMMENT ON COLUMN genre_hierarchy.genre_id          IS 'PK. The current genre in the hierarchy. References genre';
COMMENT ON COLUMN genre_hierarchy.parent_genre_id   IS 'PK. The parent of the current genre. -1 if the genre is a root genre. References genre';
COMMENT ON COLUMN genre_hierarchy.created_utc       IS 'When the record was created in UTC';
COMMENT ON COLUMN genre_hierarchy.created_by        IS 'Who created the record';
COMMENT ON COLUMN genre_hierarchy.modified_utc      IS 'When the record was modified in UTC';
COMMENT ON COLUMN genre_hierarchy.modified_by       IS 'Who modified the record';

/*
-- ==================================
-- producer_group_hierarchy
-- ==================================
*/
CREATE TABLE producer_group_membership
(
    producer_group_id   INT             NOT NULL
    , producer_id       INT             NOT NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
    , CONSTRAINT pk_producer_group_membership PRIMARY KEY (producer_group_id, producer_id)
);

ALTER TABLE producer_group_membership
ADD CONSTRAINT fk_producer_group_membership_producer_group_id
FOREIGN KEY (producer_group_id)
REFERENCES producer_group (producer_group_id);
 
ALTER TABLE producer_group_membership
ADD CONSTRAINT fk_producer_group_membership_producer_id
FOREIGN KEY (producer_id)
REFERENCES producer (producer_id);

COMMENT ON TABLE producer_group_membership IS 'Tracks producer memberships in groups';

/*
-- ==================================
-- project
-- ==================================
*/
CREATE TABLE project
(
    project_id          INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , project_name      VARCHAR(255)    NOT NULL
    , artist_group_id   INT             NOT NULL
    , scene_id          INT                 NULL
    , project_type_id   INT             NOT NULL
    , release_date      DATE            NOT NULL
    , rating            NUMERIC(4, 2)       NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc      TIMESTAMPTZ         NULL
    , modified_by       VARCHAR(255)        NULL
    , CONSTRAINT pk_project PRIMARY KEY (project_id)
);

ALTER TABLE project
ADD CONSTRAINT fk_project_artist_group_id
FOREIGN KEY (artist_group_id)
REFERENCES artist_group (artist_group_id);
 
ALTER TABLE project
ADD CONSTRAINT fk_project_scene_id
FOREIGN KEY (scene_id)
REFERENCES genre (genre_id);
 
ALTER TABLE project
ADD CONSTRAINT fk_project_project_type_id
FOREIGN KEY (project_type_id)
REFERENCES project_type (project_type_id);

COMMENT ON TABLE project                    IS 'Data about musical projects';
COMMENT ON COLUMN project.project_id        IS 'PK, IDENTITY';
COMMENT ON COLUMN project.project_name      IS 'The name of the project';
COMMENT ON COLUMN project.scene_id          IS 'The musical scene of the project. References scene';
COMMENT ON COLUMN project.project_type_id   IS 'The type of musical project';
COMMENT ON COLUMN project.release_date      IS 'The date the musical project was released';
COMMENT ON COLUMN project.rating            IS 'The overall rating of the musical project out of 10';
COMMENT ON COLUMN project.created_utc       IS 'When the record was created in UTC';
COMMENT ON COLUMN project.created_by        IS 'Who created the record';
COMMENT ON COLUMN project.modified_utc      IS 'When the record was modified in UTC';
COMMENT ON COLUMN project.modified_by       IS 'Who modified the record';

/*
-- ==================================
-- song
-- ==================================
*/
CREATE TABLE song
(
    song_id                 INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , song_name             VARCHAR(255)    NOT NULL
    , artist_group_id       INT             NOT NULL
    , project_id            INT             NOT NULL
    , producer_group_id     INT                 NULL
    , genre_id              INT             NOT NULL
    , scene_id              INT                 NULL
    , streaming_service_id INT             NOT NULL
    , duration              INT             NOT NULL
    , rating                NUMERIC(4, 2)       NULL
    , is_added              BOOLEAN         NOT NULL    DEFAULT (FALSE)
    , is_local_file         BOOLEAN         NOT NULL    DEFAULT (FALSE)
    , created_utc           TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by            VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc          TIMESTAMPTZ         NULL
    , modified_by           VARCHAR(255)        NULL
    , CONSTRAINT pk_song PRIMARY KEY (song_id)
);

ALTER TABLE song
ADD CONSTRAINT fk_song_artist_group_id
FOREIGN KEY (artist_group_id)
REFERENCES artist_group (artist_group_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_project_id
FOREIGN KEY (project_id)
REFERENCES project (project_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_producer_group_id
FOREIGN KEY (producer_group_id)
REFERENCES producer_group (producer_group_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_genre_id
FOREIGN KEY (genre_id)
REFERENCES genre (genre_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_scene_id
FOREIGN KEY (scene_id)
REFERENCES scene (scene_id);

ALTER TABLE song
ADD CONSTRAINT fk_song_streaming_service_id
FOREIGN KEY (streaming_service_id)
REFERENCES streaming_service (streaming_service_id);

ALTER TABLE song
ADD CONSTRAINT ck_song_rating
CHECK (rating >= 0.00 AND rating <= 10.00);

ALTER TABLE song
ADD CONSTRAINT ck_song_duration
CHECK (duration >= 0);

COMMENT ON TABLE song                       IS 'Data about individual songs';
COMMENT ON COLUMN song.song_id              IS 'PK, IDENTITY';
COMMENT ON COLUMN song.song_name            IS 'The name of the song';
COMMENT ON COLUMN song.artist_group_id      IS 'The group performing the song. References music_group';
COMMENT ON COLUMN song.project_id           IS 'The project the song belongs to. References project';
COMMENT ON COLUMN song.producer_group_id    IS 'The group of producers/producer that produced the song. References producer_group';
COMMENT ON COLUMN song.genre_id             IS 'The genre of the song. References genre';
COMMENT ON COLUMN song.scene_id             IS 'The scene of the song. References scene';
COMMENT ON COLUMN song.streaming_service_id IS 'The source streaming service of the song. Local files are ported from other streaming services if they are not from Apple Music. References streaming_service';
COMMENT ON COLUMN song.duration             IS 'How long the song lasts in seconds';
COMMENT ON COLUMN song.rating               IS 'The song rating out of 10';
COMMENT ON COLUMN song.is_added             IS 'Flag if the song is or is not added in my library';
COMMENT ON COLUMN song.is_local_file        IS 'Flag if the song is or is not a local file';
COMMENT ON COLUMN song.created_utc          IS 'When the record was created in UTC';
COMMENT ON COLUMN song.created_by           IS 'Who created the record';
COMMENT ON COLUMN song.modified_utc         IS 'When the record was modified in UTC';
COMMENT ON COLUMN song.modified_by          IS 'Who modified the record';
