/*
-- ==================================
-- V5__redo_membership_tables.sql
-- Changes composite primary keys in many-to-many joining tables to a single primary surrogate key with a unique index.
-- Tables: artist_group_membership, genre_hierarchy, producer_group_membership
-- ==================================
*/

/*
-- ==================================
-- Move data to temp tables
-- ==================================
*/
CREATE TEMP TABLE temp_artist_group_membership AS
SELECT * FROM artist_group_membership;

CREATE TEMP TABLE temp_genre_hierarchy AS
SELECT * FROM genre_hierarchy;

CREATE TEMP TABLE temp_producer_group_membership AS
SELECT * FROM producer_group_membership;

/*
-- ==================================
-- Drop existing tables and dependent objects
-- ==================================
*/
DROP VIEW vw_genre_hierarchy;

DROP TABLE artist_group_membership;
DROP TABLE genre_hierarchy;
DROP TABLE producer_group_membership;

/*
-- ==================================
-- Recreate artist_group_membership
-- ==================================
*/
CREATE TABLE artist_group_membership
(
    artist_group_membership_id  INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , artist_group_id           INT             NOT NULL
    , artist_id                 INT             NOT NULL
    , created_utc               TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by                VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc              TIMESTAMPTZ         NULL
    , modified_by               VARCHAR(255)        NULL
    , CONSTRAINT pk_artist_group_membership PRIMARY KEY (artist_group_membership_id)
);

CREATE UNIQUE INDEX ux__artist_group_membership__artist_group_id__artist_id
ON artist_group_membership
(
    artist_group_id
    , artist_id
);

ALTER TABLE artist_group_membership
ADD CONSTRAINT fk_artist_group_membership_group_id
FOREIGN KEY (artist_group_id)
REFERENCES artist_group (artist_group_id);
 
ALTER TABLE artist_group_membership
ADD CONSTRAINT fk_artist_group_membership_artist_id
FOREIGN KEY (artist_id)
REFERENCES artist (artist_id);

COMMENT ON TABLE artist_group_membership IS 'Tracks artist memberships in groups';

/*
-- ==================================
-- Recreate genre_hierarchy
-- ==================================
*/
CREATE TABLE genre_hierarchy
(
    genre_hierarchy_id  INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , genre_id          INT             NOT NULL
    , parent_genre_id   INT             NOT NULL
    , created_utc       TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by        VARCHAR(255)    NOT NULL    DEFAULT CURRENT_USER
    , modified_utc      TIMESTAMPTZ
    , modified_by       VARCHAR(255)
    , CONSTRAINT pk_genre_hierarchy PRIMARY KEY (genre_hierarchy_id)
);

CREATE UNIQUE INDEX ux__genre_hierarchy__parent_genre_id__genre_id
ON genre_hierarchy
(
    parent_genre_id
    , genre_id
);

ALTER TABLE genre_hierarchy
ADD CONSTRAINT fk_genre_hierarchy_genre_id
FOREIGN KEY (genre_id)
REFERENCES genre (genre_id);
 
ALTER TABLE genre_hierarchy
ADD CONSTRAINT fk_genre_hierarchy_parent_genre_id
FOREIGN KEY (parent_genre_id)
REFERENCES genre (genre_id);

COMMENT ON TABLE genre_hierarchy                    IS 'The hierarchical organization of genres';
COMMENT ON COLUMN genre_hierarchy.genre_id          IS 'The current genre in the hierarchy. References genre';
COMMENT ON COLUMN genre_hierarchy.parent_genre_id   IS 'The parent of the current genre. -1 if the genre is a root genre. References genre';
COMMENT ON COLUMN genre_hierarchy.created_utc       IS 'When the record was created in UTC';
COMMENT ON COLUMN genre_hierarchy.created_by        IS 'Who created the record';
COMMENT ON COLUMN genre_hierarchy.modified_utc      IS 'When the record was modified in UTC';
COMMENT ON COLUMN genre_hierarchy.modified_by       IS 'Who modified the record';

/*
-- ==================================
-- Recreate producer_group_membership
-- ==================================
*/
CREATE TABLE producer_group_membership
(
    producer_group_membership_id    INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY
    , producer_group_id             INT             NOT NULL
    , producer_id                   INT             NOT NULL
    , created_utc                   TIMESTAMPTZ     NOT NULL    DEFAULT (NOW() AT TIME ZONE 'UTC')
    , created_by                    VARCHAR(255)    NOT NULL    DEFAULT (CURRENT_USER)
    , modified_utc                  TIMESTAMPTZ         NULL
    , modified_by                   VARCHAR(255)        NULL
    , CONSTRAINT pk_producer_group_membership PRIMARY KEY (producer_group_membership_id)
);

CREATE UNIQUE INDEX ux__producer_group_membership__producer_group_id__producer_id
ON producer_group_membership
(
    producer_group_id
    , producer_id
);

ALTER TABLE producer_group_membership
ADD CONSTRAINT fk_producer_group_membership_producer_group_id
FOREIGN KEY (producer_group_id)
REFERENCES producer_group (producer_group_id);
 
ALTER TABLE producer_group_membership
ADD CONSTRAINT fk_producer_group_membership_producer_id
FOREIGN KEY (producer_id)
REFERENCES producer (producer_id);

COMMENT ON TABLE producer_group_membership IS 'Tracks producer memberships in groups';

/*
-- ==================================
-- Move data from temp tables to new tables
-- ==================================
*/
-- Insert data into 'artist_group_membership'
INSERT INTO artist_group_membership
(
    artist_group_id
    , artist_id
    , created_utc
    , created_by
    , modified_utc
    , modified_by
)
SELECT
    tagm.artist_group_id
    , tagm.artist_id
    , tagm.created_utc
    , tagm.created_by
    , tagm.modified_utc
    , tagm.modified_by
FROM
    temp_artist_group_membership AS tagm
;

-- Insert data into 'genre_hierarchy'
INSERT INTO genre_hierarchy 
(
    genre_id
    , parent_genre_id
    , created_utc
    , created_by
    , modified_utc
    , modified_by
)
SELECT
    tgh.genre_id
    , tgh.parent_genre_id
    , tgh.created_utc
    , tgh.created_by
    , tgh.modified_utc
    , tgh.modified_by
FROM
    temp_genre_hierarchy AS tgh
;

-- Insert data into 'producer_group_membership'
INSERT INTO producer_group_membership
(
    producer_group_id
    , producer_id
    , created_utc
    , created_by
    , modified_utc
    , modified_by
)
SELECT
    tpgm.producer_group_id
    , tpgm.producer_id
    , tpgm.created_utc
    , tpgm.created_by
    , tpgm.modified_utc
    , tpgm.modified_by
FROM
    temp_producer_group_membership AS tpgm
;


/*
-- ==================================
-- Recreate dependent objects
-- ==================================
*/
CREATE VIEW vw_genre_hierarchy
AS

/*
-- ======================================================
-- Author:        Carlos Gonzalez
-- Date Created:  2025-12-21
-- Description:   Displays the full hierarchy of the Genres and the root genre they fall under
---------------------------------------------------------
-- YYYY-MM-DD - Author - Change
-- 2026-04-26 - Carlos Gonzalez - Ported to postgres
-- ======================================================
*/

WITH RECURSIVE cte_genre_hierarchy AS
(
    -- Anchor: Get all root nodes (genres with no parent, i.e., parent_genre_id = -1)
    SELECT
        g.genre_id
        , g.genre_name
        , g.genre_name::TEXT            AS hierarchy_path
        , gh.parent_genre_id
        , 1                             AS level
        , g.genre_name                  AS root_genre
        , g.genre_id                    AS root_genre_id
    FROM
        genre AS g
        JOIN genre_hierarchy AS gh
            ON g.genre_id = gh.genre_id
    WHERE
        gh.parent_genre_id = -1
 
    UNION ALL
 
    -- Recursive: Get children of each node
    SELECT
        g.genre_id
        , g.genre_name
        , CONCAT(cte.hierarchy_path, ' > ', g.genre_name)::TEXT
        , gh.parent_genre_id
        , cte.level + 1
        , cte.root_genre
        , cte.root_genre_id
    FROM
        genre AS g
        JOIN genre_hierarchy AS gh
            ON g.genre_id = gh.genre_id
        JOIN cte_genre_hierarchy AS cte
            ON gh.parent_genre_id = cte.genre_id
    WHERE
        gh.parent_genre_id <> -1
)
SELECT
    cgh.genre_id
    , cgh.genre_name
    , cgh.hierarchy_path
    , cgh.parent_genre_id
    , cgh.level
    , cgh.root_genre
    , cgh.root_genre_id
FROM
    cte_genre_hierarchy AS cgh
;
