name: MusicApp-Database CI

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'musicapp-db/migrations/**'
      - 'musicapp-db/schema/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  migrate:
    name: musicapp-db-validation
    runs-on: self-hosted

    env:
      FLYWAY_URL: ${{ github.ref_name == 'main' && secrets.FLYWAY_URL_PROD || secrets.FLYWAY_URL_DEV}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Display current migration info
        uses: docker://flyway/flyway:11
        with:
          args: >-
            -url=${{ env.FLYWAY_URL }} 
            -user=${{ secrets.FLYWAY_USER }} 
            -password=${{ secrets.FLYWAY_PASSWORD }} 
            -locations=filesystem:/github/workspace/musicapp-db/migrations info

      - name: Validate database and migrations
        uses: docker://flyway/flyway:11
        with:
          args: >-
            -url=${{ env.FLYWAY_URL }} 
            -user=${{ secrets.FLYWAY_USER }} 
            -password=${{ secrets.FLYWAY_PASSWORD }} 
            -locations=filesystem:/github/workspace/musicapp-db/migrations validate -ignoreMigrationPatterns='*:pending'