name: Database Migrations

on:
    push:
        branches:
            - main
            - dev
        paths:
            - 'migrations/**'

jobs:
    migrate:
        name: Run Flyway Migrations
        runs-on: ubuntu-latest

        env:
          FLYWAY_URL: ${{ github.ref_name == 'main' && secrets.FLYWAY_URL_PROD || secrets.FLYWAY_URL_DEV}}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Run Flyway migrations
              uses: docker://flyway/flyway:11
              with:
                args: -url=${{ env.FLYWAY_URL }} -user=${{ secrets.FLYWAY_USER }} -password=${{ secrets.FLYWAY_PASSWORD }} -locations=filesystem:/github/workspace/migrations migrate

            - name: Print migration info
              if: always()
              uses: docker://flyway/flyway:11
              with:
                args: -url=${{ env.FLYWAY_URL }} -user=${{ secrets.FLYWAY_USER }} -password=${{ secrets.FLYWAY_PASSWORD }} -locations=filesystem:/github/workspace/migrations info